# Generated by Django 4.2.7 on 2025-05-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counto_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="party",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
