# Generated by Django 4.2.7 on 2025-05-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counto_app", "0003_remove_transaction_party_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="vendor",
        ),
        migrations.AddField(
            model_name="transaction",
            name="party",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("INCOME", "Income"), ("EXPENSE", "Expense")], max_length=10
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Vendor",
        ),
    ]
