# Generated by Django 4.2.7 on 2025-06-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counto_app', '0006_bill_billpayment_invoice_invoicepayment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('saved_filename', models.CharField(max_length=255, unique=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-upload_date'],
                'indexes': [models.Index(fields=['user', 'upload_date'], name='counto_app__user_id_e9b0d6_idx'), models.Index(fields=['user', 'original_filename'], name='counto_app__user_id_2d0882_idx')],
            },
        ),
    ]
