# Generated by Django 4.2.7 on 2025-06-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("counto_app", "0006_bill_billpayment_invoice_invoicepayment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingtransaction",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pendingtransaction",
            name="raw_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
